#
# ArtifactHub: https://artifacthub.io/packages/helm/bitnami/nginx-ingress-controller
# GitHub: https://github.com/bitnami/charts/tree/main/bitnami/nginx-ingress-controller
# Default Values: https://github.com/bitnami/charts/blob/main/bitnami/nginx-ingress-controller/values.yaml
#
replicaCount: 1

nodeSelector:
    node-role: system

ingressClassResource:
    name: nginx
    controllerClass: "k8s.io/ingress-nginx-ui"

resources:
    requests:
        cpu: "100m"
        memory: "128Mi"
    limits:
        cpu: "150m"
        memory: "192Mi"

defaultBackend:
    nodeSelector:
        node-role: system

    resources:
        requests:
            cpu: "100m"
            memory: "128Mi"
        limits:
            cpu: "150m"
            memory: "192Mi"

service:
    type: LoadBalancer

    ports:
        https: 443

    targetPort:
        http: http

    annotations:
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
